// import { NuqsAdapter } from 'nuqs/adapters/next/app'
import '@seeds/tailwind/globals.css'
import { Toaster } from '@seeds/ui/toaster'
import type { Metadata } from 'next'
import { Providers } from './providers'
import { getUserFont } from '@/lib/get-user-font'
import { getFontByName, getAllFontsClassName } from '@/lib/font-loader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: [{ media: '(prefers-color-scheme: light)' }, { media: '(prefers-color-scheme: dark)' }],
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const userFontName = await getUserFont()
  const userFont = getFontByName(userFontName)
  const allFontsClassName = getAllFontsClassName()

  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${allFontsClassName} ${userFont.className} antialiased`}>
        <Providers>
          {/* <NuqsAdapter>{children}</NuqsAdapter> */}
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
