import { Toaster } from '@seeds/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import { NuqsAdapter } from 'nuqs/adapters/next/app'
import '@seeds/tailwind/globals.css'
import { Providers } from './providers'
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: [
    { media: '(prefers-color-scheme: light)' },
    { media: '(prefers-color-scheme: dark)' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`}>
        {/* <body className={`${inter.variable} antialiased theme-mono`}> */}
        <Providers>
          {/* <NuqsAdapter>{children}</NuqsAdapter> */}
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
